/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLogin: typeof import('./src/components/Admin/AdminLogin.vue')['default']
    AdminPanel: typeof import('./src/components/Admin/AdminPanel.vue')['default']
    AdminPanelLogin: typeof import('./src/components/Admin/AdminPanelLogin.vue')['default']
    Calulator: typeof import('./src/components/Calculator/Calulator.vue')['default']
    CategoriesTable: typeof import('./src/components/Admin/CategoriesTable.vue')['default']
    CategoryExerciseRequirements: typeof import('./src/components/Calculator/CategoryExerciseRequirements.vue')['default']
    Combo: typeof import('./src/components/Calculator/Combo.vue')['default']
    Combos: typeof import('./src/components/Calculator/Combos.vue')['default']
    ElementTable: typeof import('./src/components/Admin/ElementTable.vue')['default']
    ExcersisesTable: typeof import('./src/components/Admin/ExcersisesTable.vue')['default']
    ExersisesTable: typeof import('./src/components/Admin/ExersisesTable.vue')['default']
    HelloWorld: typeof import('./src/components/Calculator/HelloWorld.vue')['default']
    LevelStats: typeof import('./src/components/Calculator/LevelStats.vue')['default']
    Requirement: typeof import('./src/components/Calculator/Requirement.vue')['default']
    Requirements: typeof import('./src/components/Calculator/Requirements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypesTable: typeof import('./src/components/Admin/TypesTable.vue')['default']
    TypeStats: typeof import('./src/components/Calculator/TypeStats.vue')['default']
  }
}
